Repository prgrms-fe-devcourse/FEDC5_dopen_Hoil, pull requests merged in 2024-01, with the labels that each got.

#30 [Fix] axios interceptors 옵션 수정
  src/apis/instance.ts
Labels: 🐛bug

#31 [Style] MainPage의 컴포넌트 너비 변경
  src/pages/MainPage/BoardListPreview.tsx
  src/pages/MainPage/Dday.tsx
  src/pages/MainPage/GuestProfile.tsx
  src/pages/MainPage/LoginProfile.tsx
Labels: 💄style

#32 [Style] MainPage BoardListPreview의 padding 값 수정
  src/pages/MainPage/BoardListPreview.tsx
Labels: 🐛bug, 💄style

#50 [Fix] PageHeader컴포넌트 width, height 프롭스 삭제 및 ...props로 스타일 받게 변경
  src/components/PageHeader/index.tsx
  src/stories/components/PageHeader.stories.ts
Labels: 💄style, :eyes: 리뷰 필요

#52 [Fix] TextIconButton 컴포넌트 내부 텍스트 스타일을 props로 받아와서 최상단 컨테이너에서 적용하게 수정(간단)
  src/components/common/TextIconButton/index.tsx
Labels: :eyes: 리뷰 필요, :wrench: fix

#55 [Style] PageHeader height 값 수정
  src/components/PageHeader/index.tsx
Labels: 🐛bug, 💄style

#63 [Style] 404Page 제작
  src/app/App.tsx
  src/assets/404.svg
  src/pages/404Page/index.tsx
  src/stories/pages/404Page/ErrorPage.stories.tsx
Labels: 💄style, :eyes: 리뷰 필요

#72 [Fix] PageHeader컴포넌트 아이콘 클릭시 페이지 이동되게 변경 및 스토리북 수정(간단)
  .storybook/preview.ts
  src/components/PageHeader/index.tsx
  src/stories/components/PageHeader.stories.ts
Labels: :wrench: fix

#78 [Hotfix] isValueUniqueInArray 수정
  src/utils/isValueUniqueInArray.ts
Labels: 🐛bug

#82 [Feature] MainPage 게시판 더보기 버튼 클릭 시 '/board' 로 넘어가게 처리
  src/pages/MainPage/BoardListPreview.tsx
Labels: :eyes: 리뷰 필요, :wrench: fix

#88 [Feature] 타이머페이지, 타이머 세팅 모달 구현(외 유틸함수 다수...)
  package-lock.json
  package.json
  src/app/App.tsx
  src/components/PageHeader/index.tsx
  src/constants/time.ts
  src/hooks/useTimer.ts
  src/hooks/useTodayTimePost.ts
  src/pages/TimerPage/TimerSettingModal/index.tsx
  src/pages/TimerPage/index.tsx
  src/stories/pages/TimerPage/TimerPage.stories.tsx
  src/test/calculateTimeDiff.test.ts
  src/test/sum.test.ts
  src/test/sum.ts
  src/theme/index.ts
  src/utils/calculateTimeDiff.test.ts
  src/utils/convertDateToString.test.ts
  src/utils/debounce.ts
  src/utils/getCurrentStringTime.test.ts
  src/utils/getCurrentStringTime.ts
  src/utils/getInteractiveMap.test.ts
  src/utils/secondsToString.test.ts
  src/utils/secondsToStringTime.ts
  src/utils/stringTimeToSeconds.test.ts
  src/utils/stringTimeToSeconds.ts
Labels: ✨feature, :eyes: 리뷰 필요

#99 [Fix] OnlineUsers Text 길이가 길어질 시 ... 처리
  src/components/OnlineUserProfile/index.tsx
  src/pages/BoardPage/OnlineUsers.tsx
Labels: 💄style, :eyes: 리뷰 필요, :wrench: fix

#104 [Fix] OnlineUserProfile username 가운데 정렬 (1줄 수정)
  src/components/OnlineUserProfile/index.tsx
Labels: 💄style

#106 [Fix] Footer컴포넌트에서 랭킹제거 (간단)
  src/components/Footer/index.tsx
  src/stories/components/Footer.stories.ts
Labels: :eyes: 리뷰 필요, :wrench: fix

#108 [Fix] useTodayTimerPost내부 날짜비교로직 수정 (간단)
  src/hooks/useTodayTimePost.ts
Labels: :eyes: 리뷰 필요, :wrench: fix

#120 [Fix] PostList 버그 수정
  src/components/PostList/index.tsx
  src/utils/checkIsJson.test.ts
  src/utils/checkIsJson.ts
Labels: 🐛bug, :eyes: 리뷰 필요

#122 [Fix] 메인헤더 아이콘 관련 수정 (간단)
  src/components/MainHeader/index.tsx
Labels: 💄style, :eyes: 리뷰 필요, :wrench: fix

#123 [Style] 페이지 헤더 아이콘 변경 (매우간단)
  src/components/PageHeader/index.tsx
Labels: 💄style

#134 [Feature] 잔디컴포넌트 상단에 년,월 추가 및 가운데정렬 (매우간단)
  src/components/Grass/index.tsx
  src/stories/components/Grass/index.stories.tsx
Labels: 💄style, :eyes: 리뷰 필요, :wrench: fix

#138 [Feature] MainPage Grass 컴포넌트 추가 (간단)
  src/pages/MainPage/GrassBox.tsx
  src/pages/MainPage/index.tsx
Labels: ✨feature, :eyes: 리뷰 필요, :wrench: fix

#143 [Hoxfix] MainPage 출력 안됨 issue 해결 && Grass 데이터 가공
  src/hooks/useStudy.ts
  src/pages/MainPage/Dday.tsx
  src/pages/MainPage/GrassBox.tsx
  src/pages/MainPage/index.tsx
Labels: 🐛bug, :eyes: 리뷰 필요, :wrench: fix

#149 [Hotfix] UseStudy hook (return문 빠진 거 급하게 수정)
  src/hooks/useStudy.ts
Labels: 🐛bug

#148 [Fix] MainPage Grass 로그인 유무에 따른 출력값 수정 (간단)
  src/constants/GrassDummy.ts
  src/pages/MainPage/index.tsx
Labels: 🐛bug, :wrench: fix

#163 [Style] Image 배포 시 에러 나는 것들 수정(파일 위치 경로 수정)
  public/assets/404.svg
  public/assets/kakao.png
  public/assets/naver.png
  public/assets/send.svg
  src/components/Comment/CommentForm.tsx
  src/pages/404Page/index.tsx
  src/pages/Login/loginInputList.ts
Labels: 💄style

#161 [Fix] 회원정보 수정 페이지(header, footer 추가)
  src/pages/MyPage/Account/index.tsx
Labels: :wrench: fix

#166 [Fix] MainPage Grass 컴포넌트 오류 해결 - 로그인 시 잔디 출력이 안되는 이슈
  src/constants/GrassDummy.ts
  src/pages/MainPage/GuestGrassBox.tsx
  src/pages/MainPage/LoginGrassBox.tsx
  src/pages/MainPage/index.tsx
Labels: 🐛bug, :eyes: 리뷰 필요, :wrench: fix

#175 [Fix] 실시간 접속자 상세 정보 확인 기능
  src/components/OnlineUserProfile/index.tsx
  src/pages/BoardPage/OnlineUsers.tsx
Labels: :wrench: fix

#183 [Styel ] MainDdayModal 텍스트 간격 수정
  src/pages/MainPage/DdayModal/index.tsx
Labels: 💄style

#185 [Fix] SearchPage 검색어 글자수 제한 및 autoFocus 추가
  src/pages/SearchPage/SearchInput.tsx
  src/pages/SearchPage/index.tsx
Labels: :wrench: fix

#186 [Style] Comment Style 수정(cursor 추가, 배경색 추가)
  src/components/Comment/CommentForm.tsx
  src/components/Comment/index.tsx
  src/components/common/UserContentBlock/index.tsx
Labels: 💄style

#191 [Fix] mobile device
  src/components/PageLayout/index.tsx
  src/pages/Login/index.tsx
Labels: 🐛bug, 💄style
